name: Close Issues on Done

on:
  project_card:
    types: [moved]
  pull_request:
    types: [closed]

jobs:
  closeIssue:
    runs-on: ubuntu-latest
    steps:
    - name: Close Issue if moved to done
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const payload = context.payload;
          if (payload.action === 'moved' && payload.project_card.column_name === 'Done') {
            const issueNumber = payload.project_card.content_url.split('/').pop();
            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');
            await octokit.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed'
            });
          }
